name: Email Step Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: 22f1000662@ds.study.iitm.ac.in
        run: echo "This step is named after my email"
